#!/bin/bash
# This script checks if a postgres server is accepting connections and is in recovery mode (reader/replica) by executing pg_is_in_recover()
# and returns a 1 or 0 accordingly for HAProxy to determin state of the backend DB
# The purpose of this script is make haproxy capable of monitoring postgres properly
# It is recommended that a low-privileged postgres  user is created to be used by this script.
# For eg. create  user healthchkusr login password 'hc321';
# HA Proxy calls this script automatically with parameters described in comments in the individual server config files
# HOSTNAME to connect is arguement number 3 and PORT to connect on is ARGUEMENT number 4

PGBIN=/usr/bin/psql
PGSQL_HOST="$3"
PGSQL_PORT="$4"
PGSQL_DATABASE="postgres"
PGSQL_USERNAME="postgres"
export PGPASSWORD=""
TMP_FILE="/tmp/pgsqlchk.out"
ERR_FILE="/tmp/pgsqlchk.err"


# We perform a simple query that should return a few results

VALUE="$( /usr/bin/psql -t -h $PGSQL_HOST -U postgres -c 'select pg_is_in_recovery();' )"
# Check the output. If it is not empty then everything is fine and we return something. Else, we just do not return anything.

if [ "$VALUE" = " t" ]
then
    exit 0
else 
    exit 1
fi
